const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"保管人员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"保管人员管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"固定资产管理",
                        "menuJump":"列表",
                        "tableName":"gudingzichan"
                    }
                ],
                "menu":"固定资产管理"
            }
			 ,{
				 "child":[
					 {
						 "buttons":[
							 "查看",
							 "新增",
							 "删除"
						 ],
						 "menu":"资产折旧管理",
						 "menuJump":"列表",
						 "tableName":"zichanzhejiu"
					 }
				 ],
				 "menu":"资产折旧管理"
			 }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "归还",
                            "删除"
                        ],
                        "menu":"资产借出管理",
                        "menuJump":"列表",
                        "tableName":"zichanjiechu"
                    }
                ],
                "menu":"资产借出管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"资产维修管理",
                        "menuJump":"列表",
                        "tableName":"zichanweixiu"
                    }
                ],
                "menu":"资产维修管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"增加方式管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryAdd"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"存放地点管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryAddress"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"使用部门管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryBumen"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"资产类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryGudingzichan"
			        }
			    ],
			    "menu":"基础数据管理"
			}
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							 "新增",
							 "修改",
							 "删除"
	                    ],
	                    "menu":"固定资产管理",
	                    "menuJump":"列表",
	                    "tableName":"gudingzichan"
	                }
	            ],
	            "menu":"固定资产管理"
	        }
			,{
				 "child":[
					 {
						 "buttons":[
							 "查看",
							 "新增",
							 "删除"
						 ],
						 "menu":"资产折旧管理",
						 "menuJump":"列表",
						 "tableName":"zichanzhejiu"
					 }
				 ],
				 "menu":"资产折旧管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                         "新增",
	                         "修改",
	                         "删除",
	                        "归还"
	                    ],
	                    "menu":"资产借出管理",
	                    "menuJump":"列表",
	                    "tableName":"zichanjiechu"
	                }
	            ],
	            "menu":"资产借出管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"新增",
	                        "修改",
							"维修",
	                        "删除"
	                    ],
	                    "menu":"资产维修管理",
	                    "menuJump":"列表",
	                    "tableName":"zichanweixiu"
	                }
	            ],
	            "menu":"资产维修管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"保管人员",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
